version: '3'

networks:
  monolithic-loadbalancer-networks:

services:

  monolithic_app_loadbalancer_container_1:
    build:
      context: ./monolithic_web
      dockerfile: Dockerfile
    environment:
      # SERVER CONFIG
      SERVER_PORT: "8000"
      SERVER_HOST: "0.0.0.0"
      # DATABASE CONFIG
      DB_NAME: "monolithic_db"
      DB_USER: "root"
      DB_PASS: "M0nOL1T1c.P0Rt4L"
      DB_HOST: "monolithic-db-loadbalancer-container" 
      DB_PORT: "3306"
    networks:
      - monolithic-loadbalancer-networks
    depends_on:
      monolithic-db-loadbalancer-container: 
        condition: service_healthy

  monolithic_app_loadbalancer_container_2:
    build:
      context: ./monolithic_web
      dockerfile: Dockerfile
    environment:
      # SERVER CONFIG
      SERVER_PORT: "8000"
      SERVER_HOST: "0.0.0.0"
      # DATABASE CONFIG
      DB_NAME: "monolithic_db"
      DB_USER: "root"
      DB_PASS: "M0nOL1T1c.P0Rt4L"
      DB_HOST: "monolithic-db-loadbalancer-container" 
      DB_PORT: "3306"
    networks:
      - monolithic-loadbalancer-networks
    depends_on:
      monolithic-db-loadbalancer-container: 
        condition: service_healthy

  monolithic_app_loadbalancer_container_3:
    build:
      context: ./monolithic_web
      dockerfile: Dockerfile
    environment:
      # SERVER CONFIG
      SERVER_PORT: "8000"
      SERVER_HOST: "0.0.0.0"
      # DATABASE CONFIG
      DB_NAME: "monolithic_db"
      DB_USER: "root"
      DB_PASS: "M0nOL1T1c.P0Rt4L"
      DB_HOST: "monolithic-db-loadbalancer-container" 
      DB_PORT: "3306"
    networks:
      - monolithic-loadbalancer-networks
    depends_on:
      monolithic-db-loadbalancer-container: 
        condition: service_healthy

  monolithic-db-loadbalancer-container:
    build:
      context: ./monolithic_database
      dockerfile: Dockerfile
    environment:
      # MYSQL DEFINITION
      MYSQL_ROOT_PASSWORD: "M0nOL1T1c.P0Rt4L"
      MYSQL_DATABASE: "monolithic_db"      
    #ports:
    #  - 3306:3306
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 40s
        retries: 10      
    networks:
      - monolithic-loadbalancer-networks

  monolithic-loadbalancer-nginx:
    build:  ./nginx
    ports:
      - 9000:80
    depends_on:
      - monolithic_app_loadbalancer_container_1
      - monolithic_app_loadbalancer_container_2
      - monolithic_app_loadbalancer_container_3
    networks:
      - monolithic-loadbalancer-networks
