version: '3'

networks:
  monolithic-networks:

services:
  monolithic-app-container:
    build:
      context: ./monolithic_web
      dockerfile: Dockerfile
    environment:
      # SERVER CONFIG
      SERVER_PORT: "8000"
      SERVER_HOST: "0.0.0.0"
      # DATABASE CONFIG
      DB_NAME: "monolithic_db"
      DB_USER: "root"
      DB_PASS: "M0nOL1T1c.P0Rt4L"
      DB_HOST: "monolithic-db-container" 
      DB_PORT: "3306"
    ports:
      - 9000:8000
    networks:
      - monolithic-networks
    depends_on:
      monolithic-db-container: 
        condition: service_healthy

  monolithic-db-container:
    build:
      context: ./monolithic_database
      dockerfile: Dockerfile
    environment:
      # MYSQL DEFINITION
      MYSQL_ROOT_PASSWORD: "M0nOL1T1c.P0Rt4L"
      MYSQL_DATABASE: "monolithic_db"
    #ports:
    #  - 3306:3306
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 40s
        retries: 10      
    networks:
      - monolithic-networks